name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev git cmake
      - name: Create build directory and run CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild .
      - name: Build project
        run: |
          cmake --build build
      - name: Test project
        run: |
          cmake --build build -t test
